spring:
  application:
    name: anniversary
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: DEBUG

